### ISSUE TITLE
Sonarqube-plugin for Businessworks 5.9

### ISSUE THREAD

**Issue by ssheru** [kapilshivarkar/SonarQube-Plugin-for-BusinessWorks6#1]
Hi Kapil,

We running Tibco BW 5.9, so the existing sonarqube plugin is not supported as it only supports v6.0.

Have you developed any plugin for v5.9, if yes can you please share.

Thanks,

**Comment by sachink6** [comment]
I am getting Null pointer exception while executing analysis using Sonar Scanner. I am trying to scan Process file in my BW project. Please help

**Comment by sachink6** [comment]
ERROR: Could not analyze the file /Users/sachinkumar/Downloads/BW/CDAR_BO_ASTI/UtilityServices/CLE-Client/CLEClientProcesses/Exception Handling/ErrorTranslator.process
java.lang.NullPointerException: null
	at com.tibco.utils.bw.model.Process.parseProcessName(Process.java:329)
	at com.tibco.utils.bw.model.Process.startParsing(Process.java:247)
	at com.tibco.businessworks6.sonar.plugin.sensor.ProcessRuleSensor.analyseFile(ProcessRuleSensor.java:106)
	at com.tibco.businessworks6.sonar.plugin.sensor.AbstractSensor.analyse(AbstractSensor.java:104)
	at com.tibco.businessworks6.sonar.plugin.sensor.AbstractRuleSensor.analyse(AbstractRuleSensor.java:119)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:302)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:297)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:271)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
